FROM node:16-bullseye

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm uninstall -g expo-cli
RUN npm install -g expo

EXPOSE 19000 19001 19002

CMD ["npx", "expo", "start", "--tunnel"]
